#############################################################################
# Generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#  Jan 02, 2024 03:21:54 PM CET  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m51" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1446x921+4+16
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 4000 4000
    wm minsize $top 120 100
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Dateimeister"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    button "$top.but48" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "Press_indir" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "from file system" 
    vTcl:DefineAlias "$top.but48" "Button1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.but48 <<SetBalloon>> {
        set ::vTcl::balloon::%W {opens file dialog}
    }
    listbox "$top.lis47" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -height 116 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground #c4c4c4 -selectforeground black -selectmode single \
        -width 256 
    $top.lis47 configure -font "TkFixedFont"
    $top.lis47 insert end text
    vTcl:DefineAlias "$top.lis47" "Listbox1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.lis47 <<SetBalloon>> {
        set ::vTcl::balloon::%W {choose a camera}
    }
    button "$top.but49" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "B_camera_press" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Select Camera" 
    vTcl:DefineAlias "$top.but49" "Button2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.but49 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Select Camera}
    }
    menu "$top.m51" \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font "TkMenuFont" -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
### SPOT dump_widget_opt A
    button "$top.but55" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "Press_outdir" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "from file system" 
    vTcl:DefineAlias "$top.but55" "Button_outdir" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.but55 <<SetBalloon>> {
        set ::vTcl::balloon::%W {opens file dialog}
    }
    entry "$top.ent56" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 224 
    vTcl:DefineAlias "$top.ent56" "Entry_camera" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    button "$top.but47" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "Press_generate" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Generate" 
    vTcl:DefineAlias "$top.but47" "Button_call" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.but47 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Call Dateimeister}
    }
    text "$top.tex48" \
        -background white -font "-family {Segoe UI} -size 8" \
        -foreground black -height 386 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 988 -wrap word 
    $top.tex48 configure -font "-family {Segoe UI} -size 8"
    $top.tex48 insert end text
    vTcl:DefineAlias "$top.tex48" "Text1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    label "$top.lab49" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font "-family Arial -size 8 -weight normal -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Label" 
    vTcl:DefineAlias "$top.lab49" "Label1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    listbox "$top.lis51" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -height 116 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground #c4c4c4 -selectforeground black -selectmode single \
        -width 142 
    $top.lis51 configure -font "TkFixedFont"
    $top.lis51 insert end text
    vTcl:DefineAlias "$top.lis51" "Listbox_gen" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.lis51 <<SetBalloon>> {
        set ::vTcl::balloon::%W {generated files}
    }
    canvas "$top.can52" \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 224 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -insertbackground black -relief ridge \
        -selectbackground #c4c4c4 -selectforeground black -width 1405 
    vTcl:DefineAlias "$top.can52" "Canvas1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    checkbutton "$top.che53" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -selectcolor #d9d9d9 -text "recursive" \
        -variable "cb1_val" 
    vTcl:DefineAlias "$top.che53" "Checkbutton1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.che53 <<SetBalloon>> {
        set ::vTcl::balloon::%W {process  subdirectories}
    }
    button "$top.but51" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "Button_exclude_all" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Exclude all" 
    vTcl:DefineAlias "$top.but51" "Button_exclude" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.but51 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Exclude all}
    }
    button "$top.but53" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "Button_include_all" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Include all" 
    vTcl:DefineAlias "$top.but53" "Button_include" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.but53 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Include all}
    }
    button "$top.but50" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "Button_be_pressed" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Browse / edit output" 
    vTcl:DefineAlias "$top.but50" "Button_be" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    button "$top.but52" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "button_undo" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Undo" 
    vTcl:DefineAlias "$top.but52" "Button_undo" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    button "$top.but54" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "button_redo" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Redo" 
    vTcl:DefineAlias "$top.but54" "Button_redo" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    checkbutton "$top.che47" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -selectcolor #d9d9d9 -text "use camera prefix" \
        -variable "cb_prefix_var" 
    vTcl:DefineAlias "$top.che47" "Checkbutton_use_camera_name" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.che47 <<SetBalloon>> {
        set ::vTcl::balloon::%W {use camera as prefix}
    }
    checkbutton "$top.che48" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -selectcolor #d9d9d9 -text "Addrelpath" \
        -variable "cb_addrelpath_var" 
    vTcl:DefineAlias "$top.che48" "Checkbutton_addrelpath" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.che48 <<SetBalloon>> {
        set ::vTcl::balloon::%W {add relative path to target}
    }
    button "$top.but56" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "button_duplicates" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Show duplicates" 
    vTcl:DefineAlias "$top.but56" "Button_duplicates" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    checkbutton "$top.che49" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -selectcolor #d9d9d9 \
        -text "copy file only when newer or not existent" \
        -variable "cb_newer_var" 
    vTcl:DefineAlias "$top.che49" "Checkbutton_newer" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.che49 <<SetBalloon>> {
        set ::vTcl::balloon::%W {if checked existing files will ohnly be overridden when they are older than the source file}
    }
    label "$top.lab47" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Label" 
    vTcl:DefineAlias "$top.lab47" "Label_num" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.lab47 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Number of images }
    }
    button "$top.but57" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Save" 
    vTcl:DefineAlias "$top.but57" "Button_save" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.but57 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Save}
    }
    button "$top.but58" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Copy" 
    vTcl:DefineAlias "$top.but58" "Button_exec" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.but58 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Execute commands}
    }
    checkbutton "$top.che50" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -selectcolor #d9d9d9 -text "show image numbers" \
        -variable "cbnum_var" 
    vTcl:DefineAlias "$top.che50" "Checkbutton_num" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.che50 <<SetBalloon>> {
        set ::vTcl::balloon::%W {image numbers in canvas}
    }
    button "$top.but59" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Delete" 
    vTcl:DefineAlias "$top.but59" "Button_delete" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.but59 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Delete from outdir}
    }
    checkbutton "$top.che60" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -selectcolor #d9d9d9 -text "Delete subdirs" \
        -variable "cbdelrelpath_var" 
    vTcl:DefineAlias "$top.che60" "Checkbutton_delrelpath" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.che60 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Delete subdirs created by copy}
    }
    listbox "$top.lis48" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -height 122 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground #c4c4c4 -selectforeground black -selectmode single \
        -width 475 -listvariable "combobox_indir" 
    $top.lis48 configure -font "TkFixedFont"
    $top.lis48 insert end text
    vTcl:DefineAlias "$top.lis48" "TCombobox_indir" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.lis48 <<SetBalloon>> {
        set ::vTcl::balloon::%W {recent indirs}
    }
    listbox "$top.lis49" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -height 122 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground #c4c4c4 -selectforeground black -width 485 \
        -listvariable "combobox_outdir" 
    $top.lis49 configure -font "TkFixedFont"
    $top.lis49 insert end text
    vTcl:DefineAlias "$top.lis49" "TCombobox_outdir" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.lis49 <<SetBalloon>> {
        set ::vTcl::balloon::%W {recent outdirs}
    }
    label "$top.lab50" \
        -activebackground #ffffff -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Label" 
    vTcl:DefineAlias "$top.lab50" "Label_indir" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    label "$top.lab51" \
        -activebackground #ffffff -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Label" 
    vTcl:DefineAlias "$top.lab51" "Label_outdir" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    button "$top.but60" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "from list" 
    vTcl:DefineAlias "$top.but60" "Button_indir_from_list" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.but60 <<SetBalloon>> {
        set ::vTcl::balloon::%W {select dir from list}
    }
    button "$top.but61" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "from list" 
    vTcl:DefineAlias "$top.but61" "Button_outdir_from_list" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.but61 <<SetBalloon>> {
        set ::vTcl::balloon::%W {select dir from list}
    }
    label "$top.lab62" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "select indir" 
    vTcl:DefineAlias "$top.lab62" "Label_select_indir" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    label "$top.lab63" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "select outdir" 
    vTcl:DefineAlias "$top.lab63" "Label_select_outdir" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but48 \
        -in $top -x 0 -relx 0.29 -y 0 -rely 0.022 -width 107 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lis47 \
        -in $top -x 0 -relx 0.035 -y 0 -rely 0.195 -width 0 -relwidth 0.187 \
        -height 0 -relheight 0.144 -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 0 -relx 0.035 -y 0 -rely 0.347 -width 87 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but55 \
        -in $top -x 0 -relx 0.636 -y 0 -rely 0.022 -width 107 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent56 \
        -in $top -x 0 -relx 0.035 -y 0 -rely 0.402 -width 224 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 0 -relx 0.035 -y 0 -rely 0.467 -width 147 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tex48 \
        -in $top -x 0 -relx 0.287 -y 0 -rely 0.25 -width 0 -relwidth 0.684 \
        -height 0 -relheight 0.419 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.616 -y 0 -rely 0.673 -width 0 -relwidth 0.35 \
        -height 0 -relheight 0.04 -anchor nw -bordermode ignore 
    place $top.lis51 \
        -in $top -x 0 -relx 0.028 -y 0 -rely 0.521 -width 0 -relwidth 0.118 \
        -height 0 -relheight 0.143 -anchor nw -bordermode ignore 
    place $top.can52 \
        -in $top -x 0 -relx 0.014 -y 0 -rely 0.717 -width 0 -relwidth 0.973 \
        -height 0 -relheight 0.243 -anchor nw -bordermode ignore 
    place $top.che53 \
        -in $top -x 0 -relx 0.041 -y 0 -rely 0.043 -width 0 -relwidth 0.076 \
        -height 0 -relheight 0.029 -anchor nw -bordermode ignore 
    place $top.but51 \
        -in $top -x 0 -relx 0.159 -y 0 -rely 0.684 -width 67 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but53 \
        -in $top -x 0 -relx 0.222 -y 0 -rely 0.684 -width 67 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but50 \
        -in $top -x 0 -relx 0.152 -y 0 -rely 0.467 -width 137 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but52 \
        -in $top -x 0 -relx 0.028 -y 0 -rely 0.684 -width 37 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but54 \
        -in $top -x 0 -relx 0.062 -y 0 -rely 0.684 -width 37 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.che47 \
        -in $top -x 0 -relx 0.104 -y 0 -rely 0.043 -width 0 -relwidth 0.091 \
        -height 0 -relheight 0.026 -anchor nw -bordermode ignore 
    place $top.che48 \
        -in $top -x 0 -relx 0.041 -y 0 -rely 0.098 -width 0 -relwidth 0.084 \
        -height 0 -relheight 0.027 -anchor nw -bordermode ignore 
    place $top.but56 \
        -in $top -x 0 -relx 0.152 -y 0 -rely 0.532 -width 137 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.che49 \
        -in $top -x 0 -relx 0.104 -y 0 -rely 0.098 -width 0 -relwidth 0.175 \
        -height 0 -relheight 0.027 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.097 -y 0 -rely 0.684 -width 0 -relwidth 0.052 \
        -height 0 -relheight 0.023 -anchor nw -bordermode ignore 
    place $top.but57 \
        -in $top -x 0 -relx 0.305 -y 0 -rely 0.684 -width 67 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but58 \
        -in $top -x 0 -relx 0.36 -y 0 -rely 0.684 -width 57 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.che50 \
        -in $top -x 0 -relx 0.159 -y 0 -rely 0.651 -width 0 -relwidth 0.105 \
        -height 0 -relheight 0.026 -anchor nw -bordermode ignore 
    place $top.but59 \
        -in $top -x 0 -relx 0.409 -y 0 -rely 0.684 -width 57 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.che60 \
        -in $top -x 0 -relx 0.457 -y 0 -rely 0.684 -width 0 -relwidth 0.042 \
        -height 0 -relheight 0.027 -anchor nw -bordermode ignore 
    place $top.lis48 \
        -in $top -x 0 -relx 0.29 -y 0 -rely 0.065 -width 0 -relwidth 0.328 \
        -height 0 -relheight 0.132 -anchor nw -bordermode ignore 
    place $top.lis49 \
        -in $top -x 0 -relx 0.636 -y 0 -rely 0.065 -width 0 -relwidth 0.335 \
        -height 0 -relheight 0.132 -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 0 -relx 0.29 -y 0 -rely 0.217 -width 0 -relwidth 0.329 \
        -height 0 -relheight 0.023 -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 0 -relx 0.636 -y 0 -rely 0.217 -width 0 -relwidth 0.335 \
        -height 0 -relheight 0.023 -anchor nw -bordermode ignore 
    place $top.but60 \
        -in $top -x 0 -relx 0.539 -y 0 -rely 0.022 -width 107 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but61 \
        -in $top -x 0 -relx 0.899 -y 0 -rely 0.022 -width 97 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab62 \
        -in $top -x 0 -relx 0.394 -y 0 -rely 0.033 -width 0 -relwidth 0.134 \
        -height 0 -relheight 0.023 -anchor nw -bordermode ignore 
    place $top.lab63 \
        -in $top -x 0 -relx 0.74 -y 0 -rely 0.033 -width 0 -relwidth 0.12 \
        -height 0 -relheight 0.023 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top2 {base} {
    global vTcl
    if {$base == ""} {
        set base .top2
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m52" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1200x600+69+70
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2564 1421
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Image"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel2" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    canvas "$top.can47" \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 493 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -insertbackground black -relief ridge \
        -selectbackground #c4c4c4 -selectforeground black -width 483 
    vTcl:DefineAlias "$top.can47" "Canvas_image" vTcl:WidgetProc "Toplevel2" 1
### SPOT dump_widget_opt A
    button "$top.but47" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Fit canvas" 
    vTcl:DefineAlias "$top.but47" "Button_fit" vTcl:WidgetProc "Toplevel2" 1
### SPOT dump_widget_opt A
    bind $top.but47 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Zoom in / out}
    }
    button "$top.but48" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Full scale" 
    vTcl:DefineAlias "$top.but48" "Button_fscale" vTcl:WidgetProc "Toplevel2" 1
### SPOT dump_widget_opt A
    bind $top.but48 <<SetBalloon>> {
        set ::vTcl::balloon::%W {full resolution}
    }
    button "$top.but49" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Exclude" 
    vTcl:DefineAlias "$top.but49" "Button_exclude" vTcl:WidgetProc "Toplevel2" 1
### SPOT dump_widget_opt A
    bind $top.but49 <<SetBalloon>> {
        set ::vTcl::balloon::%W {include / exclude}
    }
    label "$top.lab47" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Label" 
    vTcl:DefineAlias "$top.lab47" "Label_status" vTcl:WidgetProc "Toplevel2" 1
### SPOT dump_widget_opt A
    button "$top.but50" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "play / pause" 
    vTcl:DefineAlias "$top.but50" "Button_pp" vTcl:WidgetProc "Toplevel2" 1
### SPOT dump_widget_opt A
    button "$top.but51" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Restart" 
    vTcl:DefineAlias "$top.but51" "Button_restart" vTcl:WidgetProc "Toplevel2" 1
### SPOT dump_widget_opt A
    bind $top.but51 <<SetBalloon>> {
        set ::vTcl::balloon::%W {restart video from begin}
    }
    menu "$top.m52" \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font "TkMenuFont" -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
### SPOT dump_widget_opt A
    scale "$top.sca47" \
        -activebackground $vTcl(analog_color_m) \
        -background $vTcl(actual_gui_bg) -bigincrement 0.0 \
        -font "TkDefaultFont" -foreground $vTcl(actual_gui_fg) -from 1.0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -label "fps" -length 196 -resolution 1.0 -tickinterval 0.0 -to 200.0 \
        -troughcolor #d9d9d9 
    vTcl:DefineAlias "$top.sca47" "Scale_fps" vTcl:WidgetProc "Toplevel2" 1
### SPOT dump_widget_opt A
    bind $top.sca47 <<SetBalloon>> {
        set ::vTcl::balloon::%W {fps}
    }
    label "$top.lab48" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Frames per second" 
    vTcl:DefineAlias "$top.lab48" "Label_fps" vTcl:WidgetProc "Toplevel2" 1
### SPOT dump_widget_opt A
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.can47 \
        -in $top -x 0 -y 0 -width 0 -relwidth 0.75 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 0 -relx 0.783 -y 0 -rely 0.133 -width 87 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 0 -relx 0.883 -y 0 -rely 0.133 -width 87 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 0 -relx 0.783 -y 0 -rely 0.233 -width 87 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.875 -y 0 -rely 0.217 -width 0 -relwidth 0.087 \
        -height 0 -relheight 0.068 -anchor nw -bordermode ignore 
    place $top.but50 \
        -in $top -x 0 -relx 0.783 -y 0 -rely 0.333 -width 87 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but51 \
        -in $top -x 0 -relx 0.883 -y 0 -rely 0.333 -width 87 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.sca47 \
        -in $top -x 0 -relx 0.767 -y 0 -rely 0.417 -width 46 -relwidth 0 \
        -height 0 -relheight 0.327 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.775 -y 0 -rely 0.75 -width 0 -relwidth 0.095 \
        -height 0 -relheight 0.035 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top3 {base} {
    global vTcl
    if {$base == ""} {
        set base .top3
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1064x514+93+103
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1444 881
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Duplicates"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel_dupl" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    canvas "$top.can47" \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 203 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -insertbackground black -relief ridge \
        -selectbackground #c4c4c4 -selectforeground black -width 1025 
    vTcl:DefineAlias "$top.can47" "Canvas_dupl" vTcl:WidgetProc "Toplevel_dupl" 1
### SPOT dump_widget_opt A
    listbox "$top.lis48" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -height 212 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground #c4c4c4 -selectforeground black -width 604 
    $top.lis48 configure -font "TkFixedFont"
    $top.lis48 insert end text
    vTcl:DefineAlias "$top.lis48" "Listbox_dupl" vTcl:WidgetProc "Toplevel_dupl" 1
### SPOT dump_widget_opt A
    button "$top.but49" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Select Duplicate" 
    vTcl:DefineAlias "$top.but49" "Button_dupl" vTcl:WidgetProc "Toplevel_dupl" 1
### SPOT dump_widget_opt A
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.can47 \
        -in $top -x 0 -relx 0.019 -y 0 -rely 0.506 -width 0 -relwidth 0.963 \
        -height 0 -relheight 0.395 -anchor nw -bordermode ignore 
    place $top.lis48 \
        -in $top -x 0 -relx 0.028 -y 0 -rely 0.039 -width 0 -relwidth 0.568 \
        -height 0 -relheight 0.412 -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 0 -relx 0.63 -y 0 -rely 0.195 -width 137 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top4 {base} {
    global vTcl
    if {$base == ""} {
        set base .top4
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1215x695+120+78
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2564 1421
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 3"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel3" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    frame "$top.fra47" \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 399 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 361 
    vTcl:DefineAlias "$top.fra47" "Frame_camera_name" vTcl:WidgetProc "Toplevel3" 1
### SPOT dump_widget_opt A
    set site_3_0 $top.fra47
    listbox "$site_3_0.lis50" \
        -background white -disabledforeground #a3a3a3 -exportselection 0 \
        -font "TkFixedFont" -foreground $vTcl(actual_gui_fg) -height 402 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground #c4c4c4 -selectforeground black -selectmode single \
        -width 344 
    $site_3_0.lis50 configure -font "TkFixedFont"
    $site_3_0.lis50 insert end text
    vTcl:DefineAlias "$site_3_0.lis50" "Listbox_camera_name" vTcl:WidgetProc "Toplevel3" 1
### SPOT dump_widget_opt A
    bind $site_3_0.lis50 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Camera Name}
    }
    place $site_3_0.lis50 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 0.953 -height 0 \
        -relheight 1.008 -anchor nw -bordermode ignore 
    frame "$top.fra48" \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 399 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 359 
    vTcl:DefineAlias "$top.fra48" "Frame_camera_type" vTcl:WidgetProc "Toplevel3" 1
### SPOT dump_widget_opt A
    set site_3_0 $top.fra48
    listbox "$site_3_0.lis51" \
        -background white -disabledforeground #a3a3a3 -exportselection 0 \
        -font "TkFixedFont" -foreground $vTcl(actual_gui_fg) -height 402 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground #c4c4c4 -selectforeground black -selectmode single \
        -width 344 
    $site_3_0.lis51 configure -font "TkFixedFont"
    $site_3_0.lis51 insert end text
    vTcl:DefineAlias "$site_3_0.lis51" "Listbox_camera_type" vTcl:WidgetProc "Toplevel3" 1
### SPOT dump_widget_opt A
    bind $site_3_0.lis51 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Camera Image Type}
    }
    place $site_3_0.lis51 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 0.958 -height 0 \
        -relheight 1.008 -anchor nw -bordermode ignore 
    frame "$top.fra49" \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 399 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 361 
    vTcl:DefineAlias "$top.fra49" "Frame_camera_suffix" vTcl:WidgetProc "Toplevel3" 1
### SPOT dump_widget_opt A
    set site_3_0 $top.fra49
    listbox "$site_3_0.lis52" \
        -background white -disabledforeground #a3a3a3 -exportselection 0 \
        -font "TkFixedFont" -foreground $vTcl(actual_gui_fg) -height 402 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground #c4c4c4 -selectforeground black -selectmode single \
        -width 344 
    $site_3_0.lis52 configure -font "TkFixedFont"
    $site_3_0.lis52 insert end text
    vTcl:DefineAlias "$site_3_0.lis52" "Listboxcamer_suffix" vTcl:WidgetProc "Toplevel3" 1
### SPOT dump_widget_opt A
    bind $site_3_0.lis52 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Camera File Suffix}
    }
    place $site_3_0.lis52 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 0.953 -height 0 \
        -relheight 1.008 -anchor nw -bordermode ignore 
    entry "$top.ent53" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 344 
    vTcl:DefineAlias "$top.ent53" "Entry_camera_name" vTcl:WidgetProc "Toplevel3" 1
### SPOT dump_widget_opt A
    bind $top.ent53 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Enter new Camera Name}
    }
    entry "$top.ent54" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 334 
    vTcl:DefineAlias "$top.ent54" "Entry_camera_type" vTcl:WidgetProc "Toplevel3" 1
### SPOT dump_widget_opt A
    bind $top.ent54 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Enter new image type}
    }
    entry "$top.ent55" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 344 
    vTcl:DefineAlias "$top.ent55" "Entrycamera_suffix" vTcl:WidgetProc "Toplevel3" 1
### SPOT dump_widget_opt A
    bind $top.ent55 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Enter new Image Type Suffix}
    }
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra47 \
        -in $top -x 0 -relx 0.042 -y 0 -rely 0.092 -width 0 -relwidth 0.297 \
        -height 0 -relheight 0.574 -anchor nw -bordermode ignore 
    place $top.fra48 \
        -in $top -x 0 -relx 0.351 -y 0 -rely 0.092 -width 0 -relwidth 0.295 \
        -height 0 -relheight 0.574 -anchor nw -bordermode ignore 
    place $top.fra49 \
        -in $top -x 0 -relx 0.658 -y 0 -rely 0.092 -width 0 -relwidth 0.297 \
        -height 0 -relheight 0.574 -anchor nw -bordermode ignore 
    place $top.ent53 \
        -in $top -x 0 -relx 0.041 -y 0 -rely 0.029 -width 344 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent54 \
        -in $top -x 0 -relx 0.354 -y 0 -rely 0.029 -width 334 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent55 \
        -in $top -x 0 -relx 0.658 -y 0 -rely 0.029 -width 344 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}
set btop2 ""
if {$vTcl(borrow)} {
    set btop2 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop2 $vTcl(tops)] != -1} {
        set btop2 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop2
Window show .top2 $btop2
if {$vTcl(borrow)} {
    $btop2 configure -background plum
}
set btop3 ""
if {$vTcl(borrow)} {
    set btop3 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop3 $vTcl(tops)] != -1} {
        set btop3 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop3
Window show .top3 $btop3
if {$vTcl(borrow)} {
    $btop3 configure -background plum
}
set btop4 ""
if {$vTcl(borrow)} {
    set btop4 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop4 $vTcl(tops)] != -1} {
        set btop4 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop4
Window show .top4 $btop4
if {$vTcl(borrow)} {
    $btop4 configure -background plum
}

