#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Feb 22, 2024 07:40:06 PM CET  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path
import Tooltip as TT
import os

_location = os.path.dirname(__file__)

import Dateimeister_support

_bgcolor = '#d9d9d9'
_fgcolor = 'black'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

_style_code_ran = 0
def _style_code():
    global _style_code_ran
    if _style_code_ran: return        
    try: Dateimeister_support.root.tk.call('source',
                os.path.join(_location, 'themes', 'alt.tcl'))
    except: pass
    style = ttk.Style()
    style.theme_use('alt')
    style.configure('.', font = "TkDefaultFont")
    _style_code_ran = 1

import tkinter as tk
from tkinter import ttk


class Toplevel2:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("1200x600+69+70")
        top.minsize(120, 1)
        top.maxsize(2564, 1421)
        top.resizable(1,  1)
        top.title("Image")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.top = top

        self.Button_fit = tk.Button(self.top)
        self.Button_fit.place(relx=0.783, rely=0.133, height=34, width=87)
        self.Button_fit.configure(activebackground="beige")
        self.Button_fit.configure(activeforeground="black")
        self.Button_fit.configure(background="#d9d9d9")
        self.Button_fit.configure(compound='left')
        self.Button_fit.configure(disabledforeground="#a3a3a3")
        self.Button_fit.configure(font="-family {Segoe UI} -size 9")
        self.Button_fit.configure(foreground="black")
        self.Button_fit.configure(highlightbackground="#d9d9d9")
        self.Button_fit.configure(highlightcolor="black")
        self.Button_fit.configure(pady="0")
        self.Button_fit.configure(text='''Fit canvas''')
        self.Button_fit_tooltip = \
        TT.ToolTip(self.Button_fit, '''Zoom in / out''')

        self.Button_fscale = tk.Button(self.top)
        self.Button_fscale.place(relx=0.883, rely=0.133, height=34, width=87)
        self.Button_fscale.configure(activebackground="beige")
        self.Button_fscale.configure(activeforeground="black")
        self.Button_fscale.configure(background="#d9d9d9")
        self.Button_fscale.configure(compound='left')
        self.Button_fscale.configure(disabledforeground="#a3a3a3")
        self.Button_fscale.configure(font="-family {Segoe UI} -size 9")
        self.Button_fscale.configure(foreground="black")
        self.Button_fscale.configure(highlightbackground="#d9d9d9")
        self.Button_fscale.configure(highlightcolor="black")
        self.Button_fscale.configure(pady="0")
        self.Button_fscale.configure(text='''Full scale''')
        self.Button_fscale_tooltip = \
        TT.ToolTip(self.Button_fscale, '''full resolution''')

        self.Button_exclude = tk.Button(self.top)
        self.Button_exclude.place(relx=0.783, rely=0.233, height=34, width=87)
        self.Button_exclude.configure(activebackground="beige")
        self.Button_exclude.configure(activeforeground="black")
        self.Button_exclude.configure(background="#d9d9d9")
        self.Button_exclude.configure(compound='left')
        self.Button_exclude.configure(disabledforeground="#a3a3a3")
        self.Button_exclude.configure(font="-family {Segoe UI} -size 9")
        self.Button_exclude.configure(foreground="black")
        self.Button_exclude.configure(highlightbackground="#d9d9d9")
        self.Button_exclude.configure(highlightcolor="black")
        self.Button_exclude.configure(pady="0")
        self.Button_exclude.configure(text='''Exclude''')
        self.Button_exclude_tooltip = \
        TT.ToolTip(self.Button_exclude, '''include / exclude''')

        self.Label_status = tk.Label(self.top)
        self.Label_status.place(relx=0.875, rely=0.217, height=41, width=104)
        self.Label_status.configure(activebackground="#f9f9f9")
        self.Label_status.configure(activeforeground="black")
        self.Label_status.configure(anchor='w')
        self.Label_status.configure(background="#d9d9d9")
        self.Label_status.configure(compound='left')
        self.Label_status.configure(disabledforeground="#a3a3a3")
        self.Label_status.configure(font="-family {Segoe UI} -size 9")
        self.Label_status.configure(foreground="black")
        self.Label_status.configure(highlightbackground="#d9d9d9")
        self.Label_status.configure(highlightcolor="black")
        self.Label_status.configure(text='''Label''')

        self.Button_pp = tk.Button(self.top)
        self.Button_pp.place(relx=0.783, rely=0.333, height=24, width=87)
        self.Button_pp.configure(activebackground="beige")
        self.Button_pp.configure(activeforeground="black")
        self.Button_pp.configure(background="#d9d9d9")
        self.Button_pp.configure(compound='left')
        self.Button_pp.configure(disabledforeground="#a3a3a3")
        self.Button_pp.configure(font="-family {Segoe UI} -size 9")
        self.Button_pp.configure(foreground="black")
        self.Button_pp.configure(highlightbackground="#d9d9d9")
        self.Button_pp.configure(highlightcolor="black")
        self.Button_pp.configure(pady="0")
        self.Button_pp.configure(text='''play / pause''')

        self.Button_restart = tk.Button(self.top)
        self.Button_restart.place(relx=0.883, rely=0.333, height=24, width=87)
        self.Button_restart.configure(activebackground="beige")
        self.Button_restart.configure(activeforeground="black")
        self.Button_restart.configure(background="#d9d9d9")
        self.Button_restart.configure(compound='left')
        self.Button_restart.configure(disabledforeground="#a3a3a3")
        self.Button_restart.configure(font="-family {Segoe UI} -size 9")
        self.Button_restart.configure(foreground="black")
        self.Button_restart.configure(highlightbackground="#d9d9d9")
        self.Button_restart.configure(highlightcolor="black")
        self.Button_restart.configure(pady="0")
        self.Button_restart.configure(text='''Restart''')
        self.Button_restart_tooltip = \
        TT.ToolTip(self.Button_restart, '''restart video from begin''')

        self.Scale_fps =  tk.Scale(self.top, from_=1.0, to=200.0, resolution=1.0)
        self.Scale_fps.place(relx=0.767, rely=0.417, relheight=0.327
                , relwidth=0.038)
        self.Scale_fps.configure(activebackground="beige")
        self.Scale_fps.configure(background="#d9d9d9")
        self.Scale_fps.configure(font="-family {Segoe UI} -size 9")
        self.Scale_fps.configure(foreground="black")
        self.Scale_fps.configure(highlightbackground="#d9d9d9")
        self.Scale_fps.configure(highlightcolor="black")
        self.Scale_fps.configure(label="fps")
        self.Scale_fps.configure(length="196")
        self.Scale_fps.configure(troughcolor="#d9d9d9")
        self.Scale_fps_tooltip = \
        TT.ToolTip(self.Scale_fps, '''fps''')

        self.Label_fps = tk.Label(self.top)
        self.Label_fps.place(relx=0.775, rely=0.75, height=21, width=114)
        self.Label_fps.configure(activebackground="#f9f9f9")
        self.Label_fps.configure(activeforeground="black")
        self.Label_fps.configure(anchor='w')
        self.Label_fps.configure(background="#d9d9d9")
        self.Label_fps.configure(compound='left')
        self.Label_fps.configure(disabledforeground="#a3a3a3")
        self.Label_fps.configure(font="-family {Segoe UI} -size 9")
        self.Label_fps.configure(foreground="black")
        self.Label_fps.configure(highlightbackground="#d9d9d9")
        self.Label_fps.configure(highlightcolor="black")
        self.Label_fps.configure(text='''Frames per second''')


class Toplevel_messages:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("1342x740+60+52")
        top.minsize(120, 1)
        top.maxsize(2564, 1421)
        top.resizable(1,  1)
        top.title("Toplevel 4")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.top = top
        self.cb_delrelpath_var = tk.IntVar()
        self.selectedButton = tk.IntVar()

        self.Frame_messages = tk.Frame(self.top)
        self.Frame_messages.place(relx=0.262, rely=0.014, relheight=0.801
                , relwidth=0.48)
        self.Frame_messages.configure(relief='groove')
        self.Frame_messages.configure(borderwidth="2")
        self.Frame_messages.configure(relief="groove")
        self.Frame_messages.configure(background="#d9d9d9")
        self.Frame_messages.configure(highlightbackground="#d9d9d9")
        self.Frame_messages.configure(highlightcolor="black")

        self.Text_messages = tk.Text(self.Frame_messages)
        self.Text_messages.place(relx=0.0, rely=0.0, relheight=0.98
                , relwidth=0.98)
        self.Text_messages.configure(background="white")
        self.Text_messages.configure(font="TkTextFont")
        self.Text_messages.configure(foreground="black")
        self.Text_messages.configure(highlightbackground="#d9d9d9")
        self.Text_messages.configure(highlightcolor="black")
        self.Text_messages.configure(insertbackground="black")
        self.Text_messages.configure(selectbackground="#c4c4c4")
        self.Text_messages.configure(selectforeground="black")
        self.Text_messages.configure(wrap="none")

        self.Frame_errors = tk.Frame(self.top)
        self.Frame_errors.place(relx=0.745, rely=0.014, relheight=0.8
                , relwidth=0.25)
        self.Frame_errors.configure(relief='groove')
        self.Frame_errors.configure(borderwidth="2")
        self.Frame_errors.configure(relief="groove")
        self.Frame_errors.configure(background="#d9d9d9")
        self.Frame_errors.configure(highlightbackground="#d9d9d9")
        self.Frame_errors.configure(highlightcolor="black")

        self.Text_errors = tk.Text(self.Frame_errors)
        self.Text_errors.place(relx=0.0, rely=0.0, relheight=0.98
                , relwidth=0.961)
        self.Text_errors.configure(background="white")
        self.Text_errors.configure(font="TkTextFont")
        self.Text_errors.configure(foreground="black")
        self.Text_errors.configure(highlightbackground="#d9d9d9")
        self.Text_errors.configure(highlightcolor="black")
        self.Text_errors.configure(insertbackground="black")
        self.Text_errors.configure(selectbackground="#c4c4c4")
        self.Text_errors.configure(selectforeground="black")
        self.Text_errors.configure(wrap="none")

        self.Button_execute = tk.Button(self.top)
        self.Button_execute.place(relx=0.179, rely=0.919, height=34, width=77)
        self.Button_execute.configure(activebackground="beige")
        self.Button_execute.configure(activeforeground="black")
        self.Button_execute.configure(background="#d9d9d9")
        self.Button_execute.configure(compound='left')
        self.Button_execute.configure(disabledforeground="#a3a3a3")
        self.Button_execute.configure(font="-family {Segoe UI} -size 9")
        self.Button_execute.configure(foreground="black")
        self.Button_execute.configure(highlightbackground="#d9d9d9")
        self.Button_execute.configure(highlightcolor="black")
        self.Button_execute.configure(pady="0")
        self.Button_execute.configure(text='''copy''')
        self.Button_execute_tooltip = \
        TT.ToolTip(self.Button_execute, '''execute command''')

        self.Checkbutton_delrelpath = tk.Checkbutton(self.top)
        self.Checkbutton_delrelpath.place(relx=0.246, rely=0.919, relheight=0.046
                , relwidth=0.124)
        self.Checkbutton_delrelpath.configure(activebackground="beige")
        self.Checkbutton_delrelpath.configure(activeforeground="black")
        self.Checkbutton_delrelpath.configure(anchor='w')
        self.Checkbutton_delrelpath.configure(background="#d9d9d9")
        self.Checkbutton_delrelpath.configure(compound='left')
        self.Checkbutton_delrelpath.configure(disabledforeground="#a3a3a3")
        self.Checkbutton_delrelpath.configure(font="-family {Segoe UI} -size 9")
        self.Checkbutton_delrelpath.configure(foreground="black")
        self.Checkbutton_delrelpath.configure(highlightbackground="#d9d9d9")
        self.Checkbutton_delrelpath.configure(highlightcolor="black")
        self.Checkbutton_delrelpath.configure(justify='left')
        self.Checkbutton_delrelpath.configure(selectcolor="#d9d9d9")
        self.Checkbutton_delrelpath.configure(text='''delrelpath''')
        self.Checkbutton_delrelpath.configure(variable=self.cb_delrelpath_var)
        self.Checkbutton_delrelpath_tooltip = \
        TT.ToolTip(self.Checkbutton_delrelpath, '''delete copied subdirs''')

        self.Frame_script = tk.Frame(self.top)
        self.Frame_script.place(relx=0.007, rely=0.014, relheight=0.8
                , relwidth=0.25)
        self.Frame_script.configure(relief='groove')
        self.Frame_script.configure(borderwidth="2")
        self.Frame_script.configure(relief="groove")
        self.Frame_script.configure(background="#d9d9d9")
        self.Frame_script.configure(highlightbackground="#d9d9d9")
        self.Frame_script.configure(highlightcolor="black")

        self.Text_script = tk.Text(self.Frame_script)
        self.Text_script.place(relx=0.0, rely=0.0, relheight=0.98
                , relwidth=0.961)
        self.Text_script.configure(background="white")
        self.Text_script.configure(font="TkTextFont")
        self.Text_script.configure(foreground="black")
        self.Text_script.configure(highlightbackground="#d9d9d9")
        self.Text_script.configure(highlightcolor="black")
        self.Text_script.configure(insertbackground="black")
        self.Text_script.configure(selectbackground="#c4c4c4")
        self.Text_script.configure(selectforeground="black")
        self.Text_script.configure(wrap="none")

        self.Radiobutton_copyscript = tk.Radiobutton(self.top)
        self.Radiobutton_copyscript.place(relx=0.015, rely=0.85, relheight=0.047
                , relwidth=0.095)
        self.Radiobutton_copyscript.configure(activebackground="beige")
        self.Radiobutton_copyscript.configure(activeforeground="black")
        self.Radiobutton_copyscript.configure(anchor='w')
        self.Radiobutton_copyscript.configure(background="#d9d9d9")
        self.Radiobutton_copyscript.configure(compound='left')
        self.Radiobutton_copyscript.configure(disabledforeground="#a3a3a3")
        self.Radiobutton_copyscript.configure(font="-family {Segoe UI} -size 9")
        self.Radiobutton_copyscript.configure(foreground="black")
        self.Radiobutton_copyscript.configure(highlightbackground="#d9d9d9")
        self.Radiobutton_copyscript.configure(highlightcolor="black")
        self.Radiobutton_copyscript.configure(justify='left')
        self.Radiobutton_copyscript.configure(selectcolor="#d9d9d9")
        self.Radiobutton_copyscript.configure(text='''copyscript''')
        self.Radiobutton_copyscript.configure(variable=self.selectedButton)

        self.Radiobutton_deletescript = tk.Radiobutton(self.top)
        self.Radiobutton_deletescript.place(relx=0.015, rely=0.891
                , relheight=0.035, relwidth=0.086)
        self.Radiobutton_deletescript.configure(activebackground="beige")
        self.Radiobutton_deletescript.configure(activeforeground="black")
        self.Radiobutton_deletescript.configure(anchor='w')
        self.Radiobutton_deletescript.configure(background="#d9d9d9")
        self.Radiobutton_deletescript.configure(compound='left')
        self.Radiobutton_deletescript.configure(disabledforeground="#a3a3a3")
        self.Radiobutton_deletescript.configure(font="-family {Segoe UI} -size 9")
        self.Radiobutton_deletescript.configure(foreground="black")
        self.Radiobutton_deletescript.configure(highlightbackground="#d9d9d9")
        self.Radiobutton_deletescript.configure(highlightcolor="black")
        self.Radiobutton_deletescript.configure(justify='left')
        self.Radiobutton_deletescript.configure(selectcolor="#d9d9d9")
        self.Radiobutton_deletescript.configure(text='''deletescript''')
        self.Radiobutton_deletescript.configure(variable=self.selectedButton)

        self.Radiobutton_delrelpathscript = tk.Radiobutton(self.top)
        self.Radiobutton_delrelpathscript.place(relx=0.015, rely=0.93
                , relheight=0.034, relwidth=0.146)
        self.Radiobutton_delrelpathscript.configure(activebackground="beige")
        self.Radiobutton_delrelpathscript.configure(activeforeground="black")
        self.Radiobutton_delrelpathscript.configure(anchor='w')
        self.Radiobutton_delrelpathscript.configure(background="#d9d9d9")
        self.Radiobutton_delrelpathscript.configure(compound='left')
        self.Radiobutton_delrelpathscript.configure(disabledforeground="#a3a3a3")
        self.Radiobutton_delrelpathscript.configure(font="-family {Segoe UI} -size 9")
        self.Radiobutton_delrelpathscript.configure(foreground="black")
        self.Radiobutton_delrelpathscript.configure(highlightbackground="#d9d9d9")
        self.Radiobutton_delrelpathscript.configure(highlightcolor="black")
        self.Radiobutton_delrelpathscript.configure(justify='left')
        self.Radiobutton_delrelpathscript.configure(selectcolor="#d9d9d9")
        self.Radiobutton_delrelpathscript.configure(text='''delrelpathscript (view only)''')
        self.Radiobutton_delrelpathscript.configure(variable=self.selectedButton)

        self.Label_script = tk.Label(self.top)
        self.Label_script.place(relx=0.44, rely=0.878, height=60, width=583)
        self.Label_script.configure(activebackground="#f9f9f9")
        self.Label_script.configure(activeforeground="black")
        self.Label_script.configure(anchor='w')
        self.Label_script.configure(background="#d9d9d9")
        self.Label_script.configure(compound='left')
        self.Label_script.configure(disabledforeground="#a3a3a3")
        self.Label_script.configure(font="-family {Segoe UI} -size 9")
        self.Label_script.configure(foreground="black")
        self.Label_script.configure(highlightbackground="#d9d9d9")
        self.Label_script.configure(highlightcolor="black")
        self.Label_script.configure(justify='left')
        self.Label_script.configure(text='''Label''')
        self.Label_script.configure(wraplength="500")

        self.Label_messages = tk.Label(self.top)
        self.Label_messages.place(relx=0.462, rely=0.824, height=20, width=123)
        self.Label_messages.configure(activebackground="#f9f9f9")
        self.Label_messages.configure(activeforeground="black")
        self.Label_messages.configure(anchor='w')
        self.Label_messages.configure(background="#d9d9d9")
        self.Label_messages.configure(compound='left')
        self.Label_messages.configure(disabledforeground="#a3a3a3")
        self.Label_messages.configure(font="-family {Segoe UI} -size 9")
        self.Label_messages.configure(foreground="black")
        self.Label_messages.configure(highlightbackground="#d9d9d9")
        self.Label_messages.configure(highlightcolor="black")
        self.Label_messages.configure(text='''Messages''')

        self.Label_errors = tk.Label(self.top)
        self.Label_errors.place(relx=0.835, rely=0.824, height=20, width=102)
        self.Label_errors.configure(activebackground="#f9f9f9")
        self.Label_errors.configure(activeforeground="black")
        self.Label_errors.configure(anchor='w')
        self.Label_errors.configure(background="#d9d9d9")
        self.Label_errors.configure(compound='left')
        self.Label_errors.configure(disabledforeground="#a3a3a3")
        self.Label_errors.configure(font="-family {Segoe UI} -size 9")
        self.Label_errors.configure(foreground="black")
        self.Label_errors.configure(highlightbackground="#d9d9d9")
        self.Label_errors.configure(highlightcolor="black")
        self.Label_errors.configure(text='''Errors''')

        self.Label_scripttype = tk.Label(self.top)
        self.Label_scripttype.place(relx=0.052, rely=0.824, height=20, width=202)

        self.Label_scripttype.configure(activebackground="#f9f9f9")
        self.Label_scripttype.configure(activeforeground="black")
        self.Label_scripttype.configure(anchor='w')
        self.Label_scripttype.configure(background="#d9d9d9")
        self.Label_scripttype.configure(compound='left')
        self.Label_scripttype.configure(disabledforeground="#a3a3a3")
        self.Label_scripttype.configure(font="-family {Segoe UI} -size 9")
        self.Label_scripttype.configure(foreground="black")
        self.Label_scripttype.configure(highlightbackground="#d9d9d9")
        self.Label_scripttype.configure(highlightcolor="black")
        self.Label_scripttype.configure(text='''Label''')

def start_up():
    Dateimeister_support.main()

if __name__ == '__main__':
    Dateimeister_support.main()




