#############################################################################
# Generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#  Feb 06, 2024 05:24:43 PM CET  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m51" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1446x921+31+20
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 4000 4000
    wm minsize $top 120 100
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Dateimeister"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    button "$top.but48" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "Press_indir" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "from file system" 
    vTcl:DefineAlias "$top.but48" "Button1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.but48 <<SetBalloon>> {
        set ::vTcl::balloon::%W {opens file dialog}
    }
    listbox "$top.lis47" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -height 116 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground #c4c4c4 -selectforeground black -selectmode single \
        -width 256 
    $top.lis47 configure -font "TkFixedFont"
    $top.lis47 insert end text
    vTcl:DefineAlias "$top.lis47" "Listbox1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.lis47 <<SetBalloon>> {
        set ::vTcl::balloon::%W {choose a camera}
    }
    button "$top.but49" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "B_camera_press" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Select Camera" 
    vTcl:DefineAlias "$top.but49" "Button2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.but49 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Select Camera}
    }
    menu "$top.m51" \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font "TkMenuFont" -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
### SPOT dump_widget_opt A
    button "$top.but55" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "Press_outdir" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "from file system" 
    vTcl:DefineAlias "$top.but55" "Button_outdir" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.but55 <<SetBalloon>> {
        set ::vTcl::balloon::%W {opens file dialog}
    }
    entry "$top.ent56" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 224 
    vTcl:DefineAlias "$top.ent56" "Entry_camera" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    button "$top.but47" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "Press_generate" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Generate" 
    vTcl:DefineAlias "$top.but47" "Button_call" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.but47 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Call Dateimeister}
    }
    text "$top.tex48" \
        -background white -font "-family {Segoe UI} -size 8" \
        -foreground black -height 386 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 988 -wrap word 
    $top.tex48 configure -font "-family {Segoe UI} -size 8"
    $top.tex48 insert end text
    vTcl:DefineAlias "$top.tex48" "Text1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    label "$top.lab49" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 \
        -font "-family Arial -size 8 -weight normal -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Label" 
    vTcl:DefineAlias "$top.lab49" "Label1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    listbox "$top.lis51" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -height 116 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground #c4c4c4 -selectforeground black -selectmode single \
        -width 142 
    $top.lis51 configure -font "TkFixedFont"
    $top.lis51 insert end text
    vTcl:DefineAlias "$top.lis51" "Listbox_gen" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.lis51 <<SetBalloon>> {
        set ::vTcl::balloon::%W {generated files}
    }
    canvas "$top.can52" \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 224 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -insertbackground black -relief ridge \
        -selectbackground #c4c4c4 -selectforeground black -width 1405 
    vTcl:DefineAlias "$top.can52" "Canvas1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    checkbutton "$top.che53" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -selectcolor #d9d9d9 -text "recursive" \
        -variable "cb1_val" 
    vTcl:DefineAlias "$top.che53" "Checkbutton1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.che53 <<SetBalloon>> {
        set ::vTcl::balloon::%W {process  subdirectories}
    }
    button "$top.but51" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "Button_exclude_all" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Exclude all" 
    vTcl:DefineAlias "$top.but51" "Button_exclude" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.but51 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Exclude all}
    }
    button "$top.but53" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "Button_include_all" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Include all" 
    vTcl:DefineAlias "$top.but53" "Button_include" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.but53 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Include all}
    }
    button "$top.but50" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "Button_be_pressed" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Browse / edit output" 
    vTcl:DefineAlias "$top.but50" "Button_be" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    button "$top.but52" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "button_undo" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Undo" 
    vTcl:DefineAlias "$top.but52" "Button_undo" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    button "$top.but54" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "button_redo" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Redo" 
    vTcl:DefineAlias "$top.but54" "Button_redo" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    checkbutton "$top.che47" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -selectcolor #d9d9d9 -text "use camera prefix" \
        -variable "cb_prefix_var" 
    vTcl:DefineAlias "$top.che47" "Checkbutton_use_camera_name" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.che47 <<SetBalloon>> {
        set ::vTcl::balloon::%W {use camera as prefix}
    }
    checkbutton "$top.che48" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -selectcolor #d9d9d9 -text "Addrelpath" \
        -variable "cb_addrelpath_var" 
    vTcl:DefineAlias "$top.che48" "Checkbutton_addrelpath" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.che48 <<SetBalloon>> {
        set ::vTcl::balloon::%W {add relative path to target}
    }
    button "$top.but56" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "button_duplicates" \
        -compound left -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Show duplicates" 
    vTcl:DefineAlias "$top.but56" "Button_duplicates" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    checkbutton "$top.che49" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -selectcolor #d9d9d9 \
        -text "copy file only when newer or not existent" \
        -variable "cb_newer_var" 
    vTcl:DefineAlias "$top.che49" "Checkbutton_newer" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.che49 <<SetBalloon>> {
        set ::vTcl::balloon::%W {if checked existing files will ohnly be overridden when they are older than the source file}
    }
    label "$top.lab47" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Label" 
    vTcl:DefineAlias "$top.lab47" "Label_num" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.lab47 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Number of images }
    }
    button "$top.but58" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Exec" 
    vTcl:DefineAlias "$top.but58" "Button_exec" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.but58 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Execute commands}
    }
    checkbutton "$top.che50" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -selectcolor #d9d9d9 -text "show image numbers" \
        -variable "cbnum_var" 
    vTcl:DefineAlias "$top.che50" "Checkbutton_num" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.che50 <<SetBalloon>> {
        set ::vTcl::balloon::%W {image numbers in canvas}
    }
    listbox "$top.lis48" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -height 122 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground #c4c4c4 -selectforeground black -selectmode single \
        -width 475 -listvariable "combobox_indir" 
    $top.lis48 configure -font "TkFixedFont"
    $top.lis48 insert end text
    vTcl:DefineAlias "$top.lis48" "TCombobox_indir" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.lis48 <<SetBalloon>> {
        set ::vTcl::balloon::%W {recent indirs}
    }
    listbox "$top.lis49" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -height 122 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground #c4c4c4 -selectforeground black -width 485 \
        -listvariable "combobox_outdir" 
    $top.lis49 configure -font "TkFixedFont"
    $top.lis49 insert end text
    vTcl:DefineAlias "$top.lis49" "TCombobox_outdir" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.lis49 <<SetBalloon>> {
        set ::vTcl::balloon::%W {recent outdirs}
    }
    label "$top.lab50" \
        -activebackground #ffffff -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Label" 
    vTcl:DefineAlias "$top.lab50" "Label_indir" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    label "$top.lab51" \
        -activebackground #ffffff -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Label" 
    vTcl:DefineAlias "$top.lab51" "Label_outdir" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    button "$top.but60" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "from list" 
    vTcl:DefineAlias "$top.but60" "Button_indir_from_list" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.but60 <<SetBalloon>> {
        set ::vTcl::balloon::%W {select dir from list}
    }
    button "$top.but61" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "from list" 
    vTcl:DefineAlias "$top.but61" "Button_outdir_from_list" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    bind $top.but61 <<SetBalloon>> {
        set ::vTcl::balloon::%W {select dir from list}
    }
    label "$top.lab62" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "select indir" 
    vTcl:DefineAlias "$top.lab62" "Label_select_indir" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    label "$top.lab63" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "select outdir" 
    vTcl:DefineAlias "$top.lab63" "Label_select_outdir" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but48 \
        -in $top -x 0 -relx 0.29 -y 0 -rely 0.022 -width 107 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lis47 \
        -in $top -x 0 -relx 0.035 -y 0 -rely 0.195 -width 0 -relwidth 0.187 \
        -height 0 -relheight 0.143 -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 0 -relx 0.035 -y 0 -rely 0.347 -width 87 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but55 \
        -in $top -x 0 -relx 0.636 -y 0 -rely 0.022 -width 107 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent56 \
        -in $top -x 0 -relx 0.035 -y 0 -rely 0.402 -width 224 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 0 -relx 0.035 -y 0 -rely 0.467 -width 147 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tex48 \
        -in $top -x 0 -relx 0.287 -y 0 -rely 0.25 -width 0 -relwidth 0.684 \
        -height 0 -relheight 0.419 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.616 -y 0 -rely 0.673 -width 0 -relwidth 0.35 \
        -height 0 -relheight 0.04 -anchor nw -bordermode ignore 
    place $top.lis51 \
        -in $top -x 0 -relx 0.028 -y 0 -rely 0.521 -width 0 -relwidth 0.118 \
        -height 0 -relheight 0.143 -anchor nw -bordermode ignore 
    place $top.can52 \
        -in $top -x 0 -relx 0.014 -y 0 -rely 0.717 -width 0 -relwidth 0.973 \
        -height 0 -relheight 0.243 -anchor nw -bordermode ignore 
    place $top.che53 \
        -in $top -x 0 -relx 0.041 -y 0 -rely 0.043 -width 0 -relwidth 0.076 \
        -height 0 -relheight 0.028 -anchor nw -bordermode ignore 
    place $top.but51 \
        -in $top -x 0 -relx 0.159 -y 0 -rely 0.684 -width 67 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but53 \
        -in $top -x 0 -relx 0.222 -y 0 -rely 0.684 -width 67 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but50 \
        -in $top -x 0 -relx 0.152 -y 0 -rely 0.467 -width 137 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but52 \
        -in $top -x 0 -relx 0.028 -y 0 -rely 0.684 -width 37 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but54 \
        -in $top -x 0 -relx 0.062 -y 0 -rely 0.684 -width 37 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.che47 \
        -in $top -x 0 -relx 0.104 -y 0 -rely 0.043 -width 0 -relwidth 0.091 \
        -height 0 -relheight 0.026 -anchor nw -bordermode ignore 
    place $top.che48 \
        -in $top -x 0 -relx 0.041 -y 0 -rely 0.098 -width 0 -relwidth 0.084 \
        -height 0 -relheight 0.027 -anchor nw -bordermode ignore 
    place $top.but56 \
        -in $top -x 0 -relx 0.152 -y 0 -rely 0.532 -width 137 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.che49 \
        -in $top -x 0 -relx 0.104 -y 0 -rely 0.098 -width 0 -relwidth 0.175 \
        -height 0 -relheight 0.027 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.097 -y 0 -rely 0.684 -width 0 -relwidth 0.052 \
        -height 0 -relheight 0.023 -anchor nw -bordermode ignore 
    place $top.but58 \
        -in $top -x 0 -relx 0.29 -y 0 -rely 0.684 -width 57 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.che50 \
        -in $top -x 0 -relx 0.159 -y 0 -rely 0.651 -width 0 -relwidth 0.105 \
        -height 0 -relheight 0.026 -anchor nw -bordermode ignore 
    place $top.lis48 \
        -in $top -x 0 -relx 0.29 -y 0 -rely 0.065 -width 0 -relwidth 0.328 \
        -height 0 -relheight 0.131 -anchor nw -bordermode ignore 
    place $top.lis49 \
        -in $top -x 0 -relx 0.636 -y 0 -rely 0.065 -width 0 -relwidth 0.335 \
        -height 0 -relheight 0.131 -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 0 -relx 0.29 -y 0 -rely 0.217 -width 0 -relwidth 0.329 \
        -height 0 -relheight 0.023 -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 0 -relx 0.636 -y 0 -rely 0.217 -width 0 -relwidth 0.335 \
        -height 0 -relheight 0.023 -anchor nw -bordermode ignore 
    place $top.but60 \
        -in $top -x 0 -relx 0.539 -y 0 -rely 0.022 -width 107 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but61 \
        -in $top -x 0 -relx 0.899 -y 0 -rely 0.022 -width 97 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab62 \
        -in $top -x 0 -relx 0.394 -y 0 -rely 0.033 -width 0 -relwidth 0.133 \
        -height 0 -relheight 0.024 -anchor nw -bordermode ignore 
    place $top.lab63 \
        -in $top -x 0 -relx 0.74 -y 0 -rely 0.033 -width 0 -relwidth 0.12 \
        -height 0 -relheight 0.024 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top2 {base} {
    global vTcl
    if {$base == ""} {
        set base .top2
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m52" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1200x600+69+70
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2564 1421
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Image"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel2" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    canvas "$top.can47" \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 493 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -insertbackground black -relief ridge \
        -selectbackground #c4c4c4 -selectforeground black -width 483 
    vTcl:DefineAlias "$top.can47" "Canvas_image" vTcl:WidgetProc "Toplevel2" 1
### SPOT dump_widget_opt A
    button "$top.but47" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Fit canvas" 
    vTcl:DefineAlias "$top.but47" "Button_fit" vTcl:WidgetProc "Toplevel2" 1
### SPOT dump_widget_opt A
    bind $top.but47 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Zoom in / out}
    }
    button "$top.but48" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Full scale" 
    vTcl:DefineAlias "$top.but48" "Button_fscale" vTcl:WidgetProc "Toplevel2" 1
### SPOT dump_widget_opt A
    bind $top.but48 <<SetBalloon>> {
        set ::vTcl::balloon::%W {full resolution}
    }
    button "$top.but49" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Exclude" 
    vTcl:DefineAlias "$top.but49" "Button_exclude" vTcl:WidgetProc "Toplevel2" 1
### SPOT dump_widget_opt A
    bind $top.but49 <<SetBalloon>> {
        set ::vTcl::balloon::%W {include / exclude}
    }
    label "$top.lab47" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Label" 
    vTcl:DefineAlias "$top.lab47" "Label_status" vTcl:WidgetProc "Toplevel2" 1
### SPOT dump_widget_opt A
    button "$top.but50" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "play / pause" 
    vTcl:DefineAlias "$top.but50" "Button_pp" vTcl:WidgetProc "Toplevel2" 1
### SPOT dump_widget_opt A
    button "$top.but51" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Restart" 
    vTcl:DefineAlias "$top.but51" "Button_restart" vTcl:WidgetProc "Toplevel2" 1
### SPOT dump_widget_opt A
    bind $top.but51 <<SetBalloon>> {
        set ::vTcl::balloon::%W {restart video from begin}
    }
    menu "$top.m52" \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font "TkMenuFont" -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
### SPOT dump_widget_opt A
    scale "$top.sca47" \
        -activebackground $vTcl(analog_color_m) \
        -background $vTcl(actual_gui_bg) -bigincrement 0.0 \
        -font "TkDefaultFont" -foreground $vTcl(actual_gui_fg) -from 1.0 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -label "fps" -length 196 -resolution 1.0 -tickinterval 0.0 -to 200.0 \
        -troughcolor #d9d9d9 
    vTcl:DefineAlias "$top.sca47" "Scale_fps" vTcl:WidgetProc "Toplevel2" 1
### SPOT dump_widget_opt A
    bind $top.sca47 <<SetBalloon>> {
        set ::vTcl::balloon::%W {fps}
    }
    label "$top.lab48" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Frames per second" 
    vTcl:DefineAlias "$top.lab48" "Label_fps" vTcl:WidgetProc "Toplevel2" 1
### SPOT dump_widget_opt A
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.can47 \
        -in $top -x 0 -y 0 -width 0 -relwidth 0.75 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 0 -relx 0.783 -y 0 -rely 0.133 -width 87 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 0 -relx 0.883 -y 0 -rely 0.133 -width 87 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 0 -relx 0.783 -y 0 -rely 0.233 -width 87 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.875 -y 0 -rely 0.217 -width 0 -relwidth 0.087 \
        -height 0 -relheight 0.068 -anchor nw -bordermode ignore 
    place $top.but50 \
        -in $top -x 0 -relx 0.783 -y 0 -rely 0.333 -width 87 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but51 \
        -in $top -x 0 -relx 0.883 -y 0 -rely 0.333 -width 87 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.sca47 \
        -in $top -x 0 -relx 0.767 -y 0 -rely 0.417 -width 46 -relwidth 0 \
        -height 0 -relheight 0.327 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.775 -y 0 -rely 0.75 -width 0 -relwidth 0.095 \
        -height 0 -relheight 0.035 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top3 {base} {
    global vTcl
    if {$base == ""} {
        set base .top3
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1064x514+93+103
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1444 881
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Duplicates"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel_dupl" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    canvas "$top.can47" \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 203 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -insertbackground black -relief ridge \
        -selectbackground #c4c4c4 -selectforeground black -width 1025 
    vTcl:DefineAlias "$top.can47" "Canvas_dupl" vTcl:WidgetProc "Toplevel_dupl" 1
### SPOT dump_widget_opt A
    listbox "$top.lis48" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -height 212 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground #c4c4c4 -selectforeground black -width 604 
    $top.lis48 configure -font "TkFixedFont"
    $top.lis48 insert end text
    vTcl:DefineAlias "$top.lis48" "Listbox_dupl" vTcl:WidgetProc "Toplevel_dupl" 1
### SPOT dump_widget_opt A
    button "$top.but49" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Select Duplicate" 
    vTcl:DefineAlias "$top.but49" "Button_dupl" vTcl:WidgetProc "Toplevel_dupl" 1
### SPOT dump_widget_opt A
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.can47 \
        -in $top -x 0 -relx 0.019 -y 0 -rely 0.506 -width 0 -relwidth 0.963 \
        -height 0 -relheight 0.395 -anchor nw -bordermode ignore 
    place $top.lis48 \
        -in $top -x 0 -relx 0.028 -y 0 -rely 0.039 -width 0 -relwidth 0.568 \
        -height 0 -relheight 0.412 -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 0 -relx 0.63 -y 0 -rely 0.195 -width 137 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top4 {base} {
    global vTcl
    if {$base == ""} {
        set base .top4
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1215x695+120+78
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2564 1421
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel _camera"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel_camera" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    frame "$top.fra47" \
        -background $vTcl(actual_gui_bg) -height 347 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 384 
    vTcl:DefineAlias "$top.fra47" "Frame_camera_name" vTcl:WidgetProc "Toplevel_camera" 1
### SPOT dump_widget_opt A
    set site_3_0 $top.fra47
    listbox "$site_3_0.lis50" \
        -background white -disabledforeground #a3a3a3 -exportselection 0 \
        -font "TkFixedFont" -foreground $vTcl(actual_gui_fg) -height 347 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground #c4c4c4 -selectforeground black -selectmode single \
        -width 409 
    $site_3_0.lis50 configure -font "TkFixedFont"
    $site_3_0.lis50 insert end text
    vTcl:DefineAlias "$site_3_0.lis50" "Listbox_camera_name" vTcl:WidgetProc "Toplevel_camera" 1
### SPOT dump_widget_opt A
    bind $site_3_0.lis50 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Camera Name}
    }
    place $site_3_0.lis50 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 0.975 -height 0 \
        -relheight 0.974 -anchor nw -bordermode ignore 
    frame "$top.fra48" \
        -background $vTcl(actual_gui_bg) -height 400 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 350 
    vTcl:DefineAlias "$top.fra48" "Frame_camera_type" vTcl:WidgetProc "Toplevel_camera" 1
### SPOT dump_widget_opt A
    set site_3_0 $top.fra48
    listbox "$site_3_0.lis51" \
        -background white -disabledforeground #a3a3a3 -exportselection 0 \
        -font "TkFixedFont" -foreground $vTcl(actual_gui_fg) -height 402 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground #c4c4c4 -selectforeground black -selectmode single \
        -width 344 
    $site_3_0.lis51 configure -font "TkFixedFont"
    $site_3_0.lis51 insert end text
    vTcl:DefineAlias "$site_3_0.lis51" "Listbox_camera_type" vTcl:WidgetProc "Toplevel_camera" 1
### SPOT dump_widget_opt A
    bind $site_3_0.lis51 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Camera Image Type}
    }
    place $site_3_0.lis51 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 0.975 -height 0 \
        -relheight 0.974 -anchor nw -bordermode ignore 
    frame "$top.fra49" \
        -background $vTcl(actual_gui_bg) -height 400 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 350 
    vTcl:DefineAlias "$top.fra49" "Frame_camera_suffix" vTcl:WidgetProc "Toplevel_camera" 1
### SPOT dump_widget_opt A
    set site_3_0 $top.fra49
    listbox "$site_3_0.lis52" \
        -background white -disabledforeground #a3a3a3 -exportselection 0 \
        -font "TkFixedFont" -foreground $vTcl(actual_gui_fg) -height 402 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -selectbackground #c4c4c4 -selectforeground black -selectmode single \
        -width 344 
    $site_3_0.lis52 configure -font "TkFixedFont"
    $site_3_0.lis52 insert end text
    vTcl:DefineAlias "$site_3_0.lis52" "Listbox_camera_suffix" vTcl:WidgetProc "Toplevel_camera" 1
### SPOT dump_widget_opt A
    bind $site_3_0.lis52 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Camera File Suffix}
    }
    place $site_3_0.lis52 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 0.975 -height 0 \
        -relheight 0.974 -anchor nw -bordermode ignore 
    entry "$top.ent53" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 344 
    vTcl:DefineAlias "$top.ent53" "Entry_camera_name" vTcl:WidgetProc "Toplevel_camera" 1
### SPOT dump_widget_opt A
    bind $top.ent53 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Enter new Camera Name}
    }
    entry "$top.ent54" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 334 
    vTcl:DefineAlias "$top.ent54" "Entry_camera_type" vTcl:WidgetProc "Toplevel_camera" 1
### SPOT dump_widget_opt A
    bind $top.ent54 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Enter new image type}
    }
    entry "$top.ent55" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 344 
    vTcl:DefineAlias "$top.ent55" "Entrycamera_suffix" vTcl:WidgetProc "Toplevel_camera" 1
### SPOT dump_widget_opt A
    bind $top.ent55 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Enter new Image Type Suffix}
    }
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra47 \
        -in $top -x 0 -relx 0.025 -y 0 -rely 0.101 -width 0 -relwidth 0.3 \
        -height 0 -relheight 0.501 -anchor nw -bordermode ignore 
    place $top.fra48 \
        -in $top -x 0 -relx 0.35 -y 0 -rely 0.101 -width 0 -relwidth 0.3 \
        -height 0 -relheight 0.501 -anchor nw -bordermode ignore 
    place $top.fra49 \
        -in $top -x 0 -relx 0.675 -y 0 -rely 0.101 -width 0 -relwidth 0.3 \
        -height 0 -relheight 0.499 -anchor nw -bordermode ignore 
    place $top.ent53 \
        -in $top -x 0 -relx 0.025 -y 0 -rely 0.024 -width 0 -relwidth 0.3 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent54 \
        -in $top -x 0 -relx 0.35 -y 0 -rely 0.024 -width 0 -relwidth 0.3 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent55 \
        -in $top -x 0 -relx 0.675 -y 0 -rely 0.024 -width 0 -relwidth 0.3 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top5 {base} {
    global vTcl
    if {$base == ""} {
        set base .top5
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1342x740+60+52
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2564 1421
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 4"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel_messages" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    frame "$top.fra47" \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 593 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 644 
    vTcl:DefineAlias "$top.fra47" "Frame_messages" vTcl:WidgetProc "Toplevel_messages" 1
### SPOT dump_widget_opt A
    set site_3_0 $top.fra47
    text "$site_3_0.tex47" \
        -background white -font "TkTextFont" -foreground black -height 581 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 533 -wrap none 
    $site_3_0.tex47 configure -font "TkTextFont"
    $site_3_0.tex47 insert end text
    vTcl:DefineAlias "$site_3_0.tex47" "Text_messages" vTcl:WidgetProc "Toplevel_messages" 1
### SPOT dump_widget_opt A
    place $site_3_0.tex47 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 0.98 -height 0 \
        -relheight 0.98 -anchor nw -bordermode ignore 
    frame "$top.fra48" \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 596 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 330 
    vTcl:DefineAlias "$top.fra48" "Frame_errors" vTcl:WidgetProc "Toplevel_messages" 1
### SPOT dump_widget_opt A
    set site_3_0 $top.fra48
    text "$site_3_0.tex49" \
        -background white -font "TkTextFont" -foreground black -height 645 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 524 -wrap none 
    $site_3_0.tex49 configure -font "TkTextFont"
    $site_3_0.tex49 insert end text
    vTcl:DefineAlias "$site_3_0.tex49" "Text_errors" vTcl:WidgetProc "Toplevel_messages" 1
### SPOT dump_widget_opt A
    place $site_3_0.tex49 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 0.961 -height 0 \
        -relheight 0.98 -anchor nw -bordermode ignore 
    button "$top.but48" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "copy" 
    vTcl:DefineAlias "$top.but48" "Button_execute" vTcl:WidgetProc "Toplevel_messages" 1
### SPOT dump_widget_opt A
    bind $top.but48 <<SetBalloon>> {
        set ::vTcl::balloon::%W {execute command}
    }
    checkbutton "$top.che49" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -selectcolor #d9d9d9 -text "delrelpath" \
        -variable "cb_delrelpath_var" 
    vTcl:DefineAlias "$top.che49" "Checkbutton_delrelpath" vTcl:WidgetProc "Toplevel_messages" 1
### SPOT dump_widget_opt A
    bind $top.che49 <<SetBalloon>> {
        set ::vTcl::balloon::%W {delete copied subdirs}
    }
    frame "$top.fra49" \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 585 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 336 
    vTcl:DefineAlias "$top.fra49" "Frame_script" vTcl:WidgetProc "Toplevel_messages" 1
### SPOT dump_widget_opt A
    set site_3_0 $top.fra49
    text "$site_3_0.tex50" \
        -background white -font "TkTextFont" -foreground black -height 574 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 324 -wrap none 
    $site_3_0.tex50 configure -font "TkTextFont"
    $site_3_0.tex50 insert end text
    vTcl:DefineAlias "$site_3_0.tex50" "Text_script" vTcl:WidgetProc "Toplevel_messages" 1
### SPOT dump_widget_opt A
    place $site_3_0.tex50 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 0.961 -height 0 \
        -relheight 0.98 -anchor nw -bordermode ignore 
    radiobutton "$top.rad47" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -selectcolor #d9d9d9 -text "copyscript" \
        -variable "selectedButton" 
    vTcl:DefineAlias "$top.rad47" "Radiobutton_copyscript" vTcl:WidgetProc "Toplevel_messages" 1
### SPOT dump_widget_opt A
    radiobutton "$top.rad48" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -selectcolor #d9d9d9 -text "deletescript" \
        -variable "selectedButton" 
    vTcl:DefineAlias "$top.rad48" "Radiobutton_deletescript" vTcl:WidgetProc "Toplevel_messages" 1
### SPOT dump_widget_opt A
    radiobutton "$top.rad49" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -selectcolor #d9d9d9 \
        -text "delrelpathscript (view only)" -variable "selectedButton" 
    vTcl:DefineAlias "$top.rad49" "Radiobutton_delrelpathscript" vTcl:WidgetProc "Toplevel_messages" 1
### SPOT dump_widget_opt A
    label "$top.lab47" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text "Label" -wraplength 500 
    vTcl:DefineAlias "$top.lab47" "Label_script" vTcl:WidgetProc "Toplevel_messages" 1
### SPOT dump_widget_opt A
    label "$top.lab48" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Messages" 
    vTcl:DefineAlias "$top.lab48" "Label_messages" vTcl:WidgetProc "Toplevel_messages" 1
### SPOT dump_widget_opt A
    label "$top.lab49" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Errors" 
    vTcl:DefineAlias "$top.lab49" "Label_errors" vTcl:WidgetProc "Toplevel_messages" 1
### SPOT dump_widget_opt A
    label "$top.lab50" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Label" 
    vTcl:DefineAlias "$top.lab50" "Label_scripttype" vTcl:WidgetProc "Toplevel_messages" 1
### SPOT dump_widget_opt A
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra47 \
        -in $top -x 0 -relx 0.262 -y 0 -rely 0.014 -width 0 -relwidth 0.48 \
        -height 0 -relheight 0.801 -anchor nw -bordermode ignore 
    place $top.fra48 \
        -in $top -x 0 -relx 0.745 -y 0 -rely 0.014 -width 0 -relwidth 0.25 \
        -height 0 -relheight 0.8 -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 0 -relx 0.179 -y 0 -rely 0.919 -width 77 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.che49 \
        -in $top -x 0 -relx 0.246 -y 0 -rely 0.919 -width 0 -relwidth 0.124 \
        -height 0 -relheight 0.046 -anchor nw -bordermode ignore 
    place $top.fra49 \
        -in $top -x 0 -relx 0.007 -y 0 -rely 0.014 -width 0 -relwidth 0.25 \
        -height 0 -relheight 0.8 -anchor nw -bordermode ignore 
    place $top.rad47 \
        -in $top -x 0 -relx 0.015 -y 0 -rely 0.85 -width 0 -relwidth 0.095 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.rad48 \
        -in $top -x 0 -relx 0.015 -y 0 -rely 0.891 -width 0 -relwidth 0.086 \
        -height 0 -relheight 0.035 -anchor nw -bordermode ignore 
    place $top.rad49 \
        -in $top -x 0 -relx 0.015 -y 0 -rely 0.93 -width 0 -relwidth 0.146 \
        -height 0 -relheight 0.034 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.44 -y 0 -rely 0.878 -width 0 -relwidth 0.434 \
        -height 0 -relheight 0.081 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.462 -y 0 -rely 0.824 -width 0 -relwidth 0.092 \
        -height 0 -relheight 0.027 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.835 -y 0 -rely 0.824 -width 0 -relwidth 0.076 \
        -height 0 -relheight 0.027 -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 0 -relx 0.052 -y 0 -rely 0.824 -width 0 -relwidth 0.151 \
        -height 0 -relheight 0.027 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top6 {base} {
    global vTcl
    if {$base == ""} {
        set base .top6
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m50" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1400x832+22+9
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2564 1421
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 5"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel_treeview_camera" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    frame "$top.fra47" \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 795 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 1365 
    vTcl:DefineAlias "$top.fra47" "Frame_treeview" vTcl:WidgetProc "Toplevel_treeview_camera" 1
### SPOT dump_widget_opt A
    set site_3_0 $top.fra47
    ttk::style configure Treeview \
         -font  "$vTcl(actual_gui_font_treeview_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd "$site_3_0.scr48" \
        -background $vTcl(actual_gui_bg) -height 15 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 30 
    vTcl:DefineAlias "$site_3_0.scr48" "Scrolledtreeview_camera" vTcl:WidgetProc "Toplevel_treeview_camera" 1
### SPOT dump_widget_opt A

        $base.fra47.scr48.01 configure -columns "Col1, Col2, Col3" -height 4
        $base.fra47.scr48.01 configure -columns {Col1, Col2, Col3}
        $base.fra47.scr48.01 heading #0 -text {Tree}
        $base.fra47.scr48.01 heading #0 -anchor center
        $base.fra47.scr48.01 column #0 -width 643
        $base.fra47.scr48.01 column #0 -minwidth 20
        $base.fra47.scr48.01 column #0 -stretch 1
        $base.fra47.scr48.01 column #0 -anchor w
        $base.fra47.scr48.01 heading Col1, -anchor center
        $base.fra47.scr48.01 column Col1, -width 219
        $base.fra47.scr48.01 column Col1, -minwidth 20
        $base.fra47.scr48.01 column Col1, -stretch 1
        $base.fra47.scr48.01 column Col1, -anchor w
        $base.fra47.scr48.01 heading Col2, -anchor center
        $base.fra47.scr48.01 column Col2, -width 224
        $base.fra47.scr48.01 column Col2, -minwidth 20
        $base.fra47.scr48.01 column Col2, -stretch 1
        $base.fra47.scr48.01 column Col2, -anchor w
        $base.fra47.scr48.01 heading Col3 -anchor center
        $base.fra47.scr48.01 column Col3 -width 226
        $base.fra47.scr48.01 column Col3 -minwidth 20
        $base.fra47.scr48.01 column Col3 -stretch 1
        $base.fra47.scr48.01 column Col3 -anchor w
    entry "$site_3_0.ent47" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 184 
    vTcl:DefineAlias "$site_3_0.ent47" "Entry_camera" vTcl:WidgetProc "Toplevel_treeview_camera" 1
### SPOT dump_widget_opt A
    bind $site_3_0.ent47 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Enter new Cameraname}
    }
    label "$site_3_0.lab48" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Camera" 
    vTcl:DefineAlias "$site_3_0.lab48" "Label_camera" vTcl:WidgetProc "Toplevel_treeview_camera" 1
### SPOT dump_widget_opt A
    button "$site_3_0.but47" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Apply" 
    vTcl:DefineAlias "$site_3_0.but47" "Button_apply" vTcl:WidgetProc "Toplevel_treeview_camera" 1
### SPOT dump_widget_opt A
    button "$site_3_0.but48" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "New camera..." 
    vTcl:DefineAlias "$site_3_0.but48" "Button_camera_new" vTcl:WidgetProc "Toplevel_treeview_camera" 1
### SPOT dump_widget_opt A
    bind $site_3_0.but48 <<SetBalloon>> {
        set ::vTcl::balloon::%W {create a new camera}
    }
    entry "$site_3_0.ent48" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 174 
    vTcl:DefineAlias "$site_3_0.ent48" "Entry_type" vTcl:WidgetProc "Toplevel_treeview_camera" 1
### SPOT dump_widget_opt A
    bind $site_3_0.ent48 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Enter new type}
    }
    entry "$site_3_0.ent49" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 184 
    vTcl:DefineAlias "$site_3_0.ent49" "Entry_suffix" vTcl:WidgetProc "Toplevel_treeview_camera" 1
### SPOT dump_widget_opt A
    bind $site_3_0.ent49 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Enter new image file suffix}
    }
    label "$site_3_0.lab50" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Type" 
    vTcl:DefineAlias "$site_3_0.lab50" "Label_type" vTcl:WidgetProc "Toplevel_treeview_camera" 1
### SPOT dump_widget_opt A
    label "$site_3_0.lab51" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Suffix" 
    vTcl:DefineAlias "$site_3_0.lab51" "Label_suffix" vTcl:WidgetProc "Toplevel_treeview_camera" 1
### SPOT dump_widget_opt A
    label "$site_3_0.lab47" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Subdir" 
    vTcl:DefineAlias "$site_3_0.lab47" "Label_subdir" vTcl:WidgetProc "Toplevel_treeview_camera" 1
### SPOT dump_widget_opt A
    entry "$site_3_0.ent50" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 364 
    vTcl:DefineAlias "$site_3_0.ent50" "Entry_subdir" vTcl:WidgetProc "Toplevel_treeview_camera" 1
### SPOT dump_widget_opt A
    bind $site_3_0.ent50 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Enter subdir for type}
    }
    button "$site_3_0.but49" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Cancel" 
    vTcl:DefineAlias "$site_3_0.but49" "Button_cancel" vTcl:WidgetProc "Toplevel_treeview_camera" 1
### SPOT dump_widget_opt A
    bind $site_3_0.but49 <<SetBalloon>> {
        set ::vTcl::balloon::%W {cancel transaction}
    }
    button "$site_3_0.but50" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "undo" 
    vTcl:DefineAlias "$site_3_0.but50" "Button_undo" vTcl:WidgetProc "Toplevel_treeview_camera" 1
### SPOT dump_widget_opt A
    bind $site_3_0.but50 <<SetBalloon>> {
        set ::vTcl::balloon::%W {undo apply}
    }
    button "$site_3_0.but51" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "redo" 
    vTcl:DefineAlias "$site_3_0.but51" "Button_redo" vTcl:WidgetProc "Toplevel_treeview_camera" 1
### SPOT dump_widget_opt A
    bind $site_3_0.but51 <<SetBalloon>> {
        set ::vTcl::balloon::%W {redo apply}
    }
    place $site_3_0.scr48 \
        -in $site_3_0 -x 0 -relx 0.015 -y 0 -rely 0.026 -width 0 \
        -relwidth 0.975 -height 0 -relheight 0.866 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent47 \
        -in $site_3_0 -x 0 -relx 0.103 -y 0 -rely 0.906 -width 184 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 0 -relx 0.103 -y 0 -rely 0.956 -width 0 \
        -relwidth 0.127 -height 0 -relheight 0.025 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but47 \
        -in $site_3_0 -x 0 -relx 0.813 -y 0 -rely 0.906 -width 97 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but48 \
        -in $site_3_0 -x 0 -relx 0.015 -y 0 -rely 0.906 -width 97 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent48 \
        -in $site_3_0 -x 0 -relx 0.249 -y 0 -rely 0.906 -width 174 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent49 \
        -in $site_3_0 -x 0 -relx 0.388 -y 0 -rely 0.906 -width 184 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 0 -relx 0.249 -y 0 -rely 0.956 -width 0 \
        -relwidth 0.133 -height 0 -relheight 0.025 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -relx 0.388 -y 0 -rely 0.956 -width 0 \
        -relwidth 0.097 -height 0 -relheight 0.026 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.535 -y 0 -rely 0.956 -width 0 \
        -relwidth 0.114 -height 0 -relheight 0.026 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent50 \
        -in $site_3_0 -x 0 -relx 0.535 -y 0 -rely 0.906 -width 364 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 0 -relx 0.894 -y 0 -rely 0.906 -width 87 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but50 \
        -in $site_3_0 -x 0 -relx 0.813 -y 0 -rely 0.956 -width 47 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but51 \
        -in $site_3_0 -x 0 -relx 0.85 -y 0 -rely 0.956 -width 47 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    menu "$top.m50" \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font "TkMenuFont" -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
### SPOT dump_widget_opt A
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra47 \
        -in $top -x 0 -relx 0.014 -y 0 -rely 0.012 -width 0 -relwidth 0.975 \
        -height 0 -relheight 0.956 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}
set btop2 ""
if {$vTcl(borrow)} {
    set btop2 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop2 $vTcl(tops)] != -1} {
        set btop2 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop2
Window show .top2 $btop2
if {$vTcl(borrow)} {
    $btop2 configure -background plum
}
set btop3 ""
if {$vTcl(borrow)} {
    set btop3 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop3 $vTcl(tops)] != -1} {
        set btop3 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop3
Window show .top3 $btop3
if {$vTcl(borrow)} {
    $btop3 configure -background plum
}
set btop4 ""
if {$vTcl(borrow)} {
    set btop4 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop4 $vTcl(tops)] != -1} {
        set btop4 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop4
Window show .top4 $btop4
if {$vTcl(borrow)} {
    $btop4 configure -background plum
}
set btop5 ""
if {$vTcl(borrow)} {
    set btop5 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop5 $vTcl(tops)] != -1} {
        set btop5 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop5
Window show .top5 $btop5
if {$vTcl(borrow)} {
    $btop5 configure -background plum
}
set btop6 ""
if {$vTcl(borrow)} {
    set btop6 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop6 $vTcl(tops)] != -1} {
        set btop6 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop6
Window show .top6 $btop6
if {$vTcl(borrow)} {
    $btop6 configure -background plum
}

