@REM  generated by dateimeister 20240108-15:23:01
del /Q "E:\Arbeit\python\Dateimeister\Daten\NAS\video\OTHER_v1.mp4"
del /Q "E:\Arbeit\python\Dateimeister\Daten\NAS\video\OTHER__AVI.avi"
del /Q "E:\Arbeit\python\Dateimeister\Daten\NAS\video\OTHER__Burda.mp4"
del /Q "E:\Arbeit\python\Dateimeister\Daten\NAS\video\OTHER__Mov.mov"
del /Q "E:\Arbeit\python\Dateimeister\Daten\NAS\video\bearbeitet\OTHER__Burda.mp4"
del /Q "E:\Arbeit\python\Dateimeister\Daten\NAS\video\bearbeitet\OTHER__Mov.mov"
