@REM  generated by dateimeister 20240108-15:23:01
echo D|xcopy /Y "E:\Fotos\Dateimeister\v1.mp4" "E:\Arbeit\python\Dateimeister\Daten\NAS\video\OTHER_v1.mp4"
echo D|xcopy /Y "E:\Fotos\Dateimeister\_AVI.avi" "E:\Arbeit\python\Dateimeister\Daten\NAS\video\OTHER__AVI.avi"
echo D|xcopy /Y "E:\Fotos\Dateimeister\_Burda.mp4" "E:\Arbeit\python\Dateimeister\Daten\NAS\video\OTHER__Burda.mp4"
echo D|xcopy /Y "E:\Fotos\Dateimeister\_Mov.mov" "E:\Arbeit\python\Dateimeister\Daten\NAS\video\OTHER__Mov.mov"
echo D|xcopy /Y "E:\Fotos\Dateimeister\bearbeitet\_Burda.mp4" "E:\Arbeit\python\Dateimeister\Daten\NAS\video\bearbeitet\OTHER__Burda.mp4"
echo D|xcopy /Y "E:\Fotos\Dateimeister\bearbeitet\_Mov.mov" "E:\Arbeit\python\Dateimeister\Daten\NAS\video\bearbeitet\OTHER__Mov.mov"
