@REM  generated by dateimeister 20231122-20:51:12
echo D|xcopy /Y "E:\Fotos\Dateimeister\v1.mp4" "E:/Arbeit/python/Dateimeister/Daten/NAS/video/MP4/OTHER_v1.mp4"
echo D|xcopy /Y "E:\Fotos\Dateimeister\_Burda.mp4" "E:/Arbeit/python/Dateimeister/Daten/NAS/video/MP4/OTHER__Burda.mp4"
