@REM  generated by dateimeister 20240108-15:39:04
echo D|xcopy /Y "E:\Fotos\Dateimeister\PIC_GH4_P1200071.RW2" "E:\Arbeit\python\Dateimeister\Daten\NAS\photo\RAW\OTHER_PIC_GH4_P1200071.RW2"
echo D|xcopy /Y "E:\Fotos\Dateimeister\PIC_GH4_P1200072.RW2" "E:\Arbeit\python\Dateimeister\Daten\NAS\photo\RAW\OTHER_PIC_GH4_P1200072.RW2"
echo D|xcopy /Y "E:\Fotos\Dateimeister\PIC_GH4_P1200073.RW2" "E:\Arbeit\python\Dateimeister\Daten\NAS\photo\RAW\OTHER_PIC_GH4_P1200073.RW2"
echo D|xcopy /Y "E:\Fotos\Dateimeister\PIC_GH4_P1200074.RW2" "E:\Arbeit\python\Dateimeister\Daten\NAS\photo\RAW\OTHER_PIC_GH4_P1200074.RW2"
echo D|xcopy /Y "E:\Fotos\Dateimeister\PIC_GH4_P1200076.RW2" "E:\Arbeit\python\Dateimeister\Daten\NAS\photo\RAW\OTHER_PIC_GH4_P1200076.RW2"
echo D|xcopy /Y "E:\Fotos\Dateimeister\xPIC_GH4_P1200069.RW2" "E:\Arbeit\python\Dateimeister\Daten\NAS\photo\RAW\OTHER_xPIC_GH4_P1200069.RW2"
